---

- name: get stable version of kubectl
  uri:
    url: https://storage.googleapis.com/kubernetes-release/release/stable.txt
    return_content: yes
    body_format: raw
  register: kubectl_version

- name: install kubectl
  uri:
    url: https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version.content }}/bin/linux/amd64/kubectl
    creates: /usr/local/bin/kubectl
    dest: /usr/local/bin/kubectl
    mode: a+x

- name: install oc
  unarchive:
    src: https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
    creates: /usr/local/bin/oc
    dest: /usr/local/bin/
    mode: a+x
    exclude:
      - README.md
    remote_src: yes
