---

- name: ensuring a checkout of assisted-test-infra exists
  git:
    repo: 'https://github.com/openshift/assisted-test-infra.git'
    dest: /home/test/assisted-test-infra
    update: no

- name: build image
  make:
    chdir: /home/test/assisted-test-infra
    target: image_build

- name: configure environment
  make:
    chdir: /home/test/assisted-test-infra
    target: create_full_environment
    params:
      NO_MINIKUBE: "true"

- name: install xinet
  package:
    name: xinetd
    state: present

- name: start firewalld
  service:
    name: firewalld
    state: started
